logos:
  light:
    image: ../../assets/images/brand/logos/light/image.png
    alt: ACOSA Logo
  dark:
    image: ../../assets/images/brand/logos/dark/image.png
    alt: ACOSA Logo
footerDescription: >-
  ACOSA connects business travellers and corporate accommodation bookers with carefully selected independent properties in key South African business nodes.
defaultWhatsapp: '+27 76 519 0092'
enquiryEmail: info@acosa.co.za
phone: '+27 76 519 0092'
socialLinks:
  - label: LinkedIn
    url: https://www.linkedin.com/company/acosaza/?lipi=urn%3Ali%3Apage%3Ap_mwlite_search_srp_all%3BSik319FES2ODaDrfkdJl9A%3D%3D
  # - label: Instagram
  #   url: https://www.instagram.com/acosa
